version: '2'
services:
    tindev-app:
        image: tindev
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tindev-mysql:3306/tindev?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tindev-mysql:
        extends:
            file: mysql.yml
            service: tindev-mysql
